on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test current build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build services from docker compose file
        run: docker-compose up --build

      - name: Run unit tests
        run: docker-compose run api yarn test

      - name: Run e2e tests
        run: docker-compose run api yarn test:e2e

  # Use this if using docker
  # build:
  #   name: Build, push image to Docker Hub
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout master
  #       uses: actions/checkout@master

  #     - name: Build and push Docker images
  #       uses: docker/build-push-action@master
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: ${{ secrets.DOCKER_USERNAME }}/test-api
  #         tag_with_ref: true

  deploy:
    name: Deploy to production server
    # needs: build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server and run deploy script in workspace folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          # Use this if using docker
          # script: |
          #   cd nest-template
          #   echo 'Pulling latest changes'
          #   git pull
          #   echo 'Running deploy script'
          #   sh commands/deploy.sh
          script: |
            source ~/.bash_profile
            pm2 -v
            cd nest-template
            bash ./deploy.sh
